services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:${PASSWORD}@${DB_HOST}:5432/beanrfid

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
